---
title: "classtpx/maptpx on Blakeley et al 2015"
author: "Kushal K Dey"
date: "March 23, 2016"
output: 
  html_document:
    css: floating-toc.css
    toc: true
---

## Introduction

We apply the `classtpx` package for topic model classfication on the [Blakeley et al 2015](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4582176/). The data for this package is saved as an ExpressionSet object at the following [link](https://github.com/kkdey/singleCellRNASeqHumanBlakeleyEmbryo). We first load the data.

```{r warning=FALSE, message=FALSE}
# devtools::install_github("kkdey/singleCellRNASeqHumanBlakeleyEmbryo", force=TRUE)
library("singleCellRNASeqHumanBlakeleyEmbryo")
data("HumanBlakeleyEmbryo")
```

```{r}
counts_data <- t(Biobase::exprs(HumanBlakeleyEmbryo));
pheno_metadata <- pData(HumanBlakeleyEmbryo);
table(pheno_metadata[,1])
```

## maptpx application

```{r echo=TRUE, eval=FALSE}
Topic_clus <- maptpx::topics(counts_data, 3, tol=0.1);
save(Topic_clus, file="../rdas/blakeley_topic_fit_3_maptpx.rda")
```

```{r echo=TRUE, eval=TRUE, warning=FALSE, fig.show="asis", dpi=144, fig.width=3, fig.height=5}
Topic_clus <- get(load(file="../rdas/blakeley_topic_fit_3_maptpx.rda"))

omega <- Topic_clus$omega;

annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(pheno_metadata[,1])
)

rownames(omega) <- annotation$sample_id;


CountClust::StructureGGplot(omega = omega,
                annotation = annotation,
                palette = RColorBrewer::brewer.pal(8, "Accent"),
                yaxis_label = "Cell cycle phase",
                order_sample = TRUE,
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
```

## classtpx

We pick first three cells from TE, PE and the EPI stages and perform classtpx. 

```{r echo=TRUE, eval=TRUE}
TE_indices <- which(pheno_metadata[,1]=="TE")[1:3];
PE_indices <- which(pheno_metadata[,1]=="PE")[1:3];
EPI_indices <- which(pheno_metadata[,1]=="EPI")[1:3];

known_samples <- c(TE_indices, PE_indices, EPI_indices);
class_labs <- c(rep(1,3), rep(2,3), rep(3,3));
```

### omega.fix method K=3

```{r echo=TRUE, eval=FALSE}
Topic_clus <- classtpx::class_topics(
    counts_data, 
    K=3, 
    known_samples = known_samples,
    class_labs = class_labs,
    method="omega.fix",
    tol=0.01,
    shrink=FALSE)

save(Topic_clus, file="../rdas/blakeley_topic_fit_3_classtpx_omega_fix.rda")

```

```{r echo=TRUE, eval=TRUE, warning=FALSE, fig.show="asis", dpi=144, fig.width=3, fig.height=5}
Topic_clus <- get(load(file="../rdas/blakeley_topic_fit_3_classtpx_omega_fix.rda"))

omega <- Topic_clus$omega;

annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(pheno_metadata[,1])
)

rownames(omega) <- annotation$sample_id;


CountClust::StructureGGplot(omega = omega,
                annotation = annotation,
                palette = RColorBrewer::brewer.pal(8, "Accent"),
                yaxis_label = "Cell cycle phase",
                order_sample = TRUE,
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
```

### theta.fix method K=3

```{r echo=TRUE, eval=FALSE}
Topic_clus <- classtpx::class_topics(
    counts_data, 
    K=3, 
    known_samples = known_samples,
    class_labs = class_labs,
    method="theta.fix",
    tol=0.01,
    shrink=FALSE)

save(Topic_clus, file="../rdas/blakeley_topic_fit_3_classtpx_theta_fix.rda")

```

```{r echo=TRUE, eval=TRUE, warning=FALSE, fig.show="asis", dpi=144, fig.width=3, fig.height=5}
Topic_clus <- get(load(file="../rdas/blakeley_topic_fit_3_classtpx_theta_fix.rda"))

omega <- Topic_clus$omega;

annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(pheno_metadata[,1])
)

rownames(omega) <- annotation$sample_id;


CountClust::StructureGGplot(omega = omega,
                annotation = annotation,
                palette = RColorBrewer::brewer.pal(8, "Accent"),
                yaxis_label = "Cell cycle phase",
                order_sample = TRUE,
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
```
