---
title: "Deng classtpx vs SVM"
author: "Kushal K Dey"
date: "May 5, 2016"
output: 
  html_document:
    css: floating-toc.css
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r warning=FALSE, message=FALSE}
library(data.table)
library(e1071)
library(classtpx)
library(maptpx)
```

```{r echo=TRUE, eval=FALSE}
#devtools::install_github("kkdey/singleCellRNASeqMouseDeng2014")
library(singleCellRNASeqMouseDeng2014)
data(Deng2014MouseEsc)
metadata <- pData(Deng2014MouseESC)
cell_type <- metadata$cell_type

inds_class <- numeric()
labels_class <- numeric()

for(k in 1:length(unique(cell_type))){
  inds <- which(cell_type == unique(cell_type)[k]);
  inds_class <- c(inds_class, inds[1:(ceiling(0.1*(length(inds)))+1)])
  labels_class <- c(labels_class, rep(k, (ceiling(0.1*(length(inds)))+1)))
}

counts <- t(exprs(Deng2014MouseESC))

```

We fit the classtpx model.

```{r echo=TRUE, eval=TRUE}
class_labs <- labels_class
known_samples <- inds_class

Topic_clus <- classtpx::class_topics(
    counts, 
    K=length(unique(cell_type)), 
    known_samples = known_samples,
    class_labs = class_labs,
    method="theta.fix",
    shrink=TRUE,
    shrink.method = 1,
    tol=0.0001,
    ord=FALSE)

save(Topic_clus, file="../rdas/deng_theta_fix_classtpx_voom.rda")


```


```{r echo=TRUE, eval=TRUE}

Topic_clus <- get(load("../rdas/deng_theta_fix_classtpx_voom.rda"))

omega <- Topic_clus$omega
annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(rownames(omega),
                        levels = rev( c("zy", "early2cell",
                                        "mid2cell", "late2cell",
                                        "4cell", "8cell", "16cell",
                                        "earlyblast","midblast",
                                         "lateblast") ) ) )

rownames(omega) <- annotation$sample_id;

cols1 <- c(rev(RColorBrewer::brewer.pal(12, "Paired"))[c(3,4,7,8,11,12,5,6,9,10)],
           RColorBrewer::brewer.pal(12, "Set3")[c(1,2,5,8,9)],
           RColorBrewer::brewer.pal(9, "Set1")[c(9,7)],
           RColorBrewer::brewer.pal(8, "Dark2")[c(3,4,8)])



CountClust::StructureGGplot(omega = omega,
                annotation = annotation,
                palette = cols1[1:11],
                yaxis_label = "Development Phase",
                order_sample = TRUE,
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

test_class_classtpx <- as.character(unique(cell_type))[apply(omega,1,function(x) which.max(x))];
tab_class_classtpx <- table(cell_type[-known_samples],
      test_class_classtpx[-known_samples]);

print(tab_class_classtpx)
sum(diag(tab_class_classtpx[rownames(tab_class_classtpx) %in% colnames(tab_class_classtpx), ]))
misclass_classtpx <- 1 - (sum(diag(tab_class_classtpx[rownames(tab_class_classtpx) %in% colnames(tab_class_classtpx), ]))/ sum(tab_class_classtpx))
misclass_classtpx

print(tab_class_classtpx)


```


```{r echo=TRUE, eval=TRUE}
class_labs <- labels_class
known_samples <- inds_class

Topic_clus <- classtpx::class_topics(
    counts, 
    K=length(unique(cell_type)), 
    known_samples = known_samples,
    class_labs = class_labs,
    method="theta.fix",
    shrink=FALSE,
    shrink.method = 1,
    tol=0.0001,
    ord=FALSE)

save(Topic_clus, file="../rdas/deng_theta_fix_classtpx_no_shrink.rda")


```


```{r echo=TRUE, eval=TRUE}

Topic_clus <- get(load(""../rdas/deng_theta_fix_classtpx_no_shrink.rda""))

omega <- Topic_clus$omega
annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(rownames(omega),
                        levels = rev( c("zy", "early2cell",
                                        "mid2cell", "late2cell",
                                        "4cell", "8cell", "16cell",
                                        "earlyblast","midblast",
                                         "lateblast") ) ) )

rownames(omega) <- annotation$sample_id;

CountClust::StructureGGplot(omega = omega,
                annotation = annotation,
                palette = RColorBrewer::brewer.pal(8, "Accent"),
                yaxis_label = "Development Phase",
                order_sample = TRUE,
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

test_class_classtpx <- as.character(unique(cell_type))[apply(omega,1,function(x) which.max(x))];
tab_class_classtpx <- table(cell_type[-known_samples],
      test_class_classtpx[-known_samples]);

print(tab_class_classtpx)
sum(diag(tab_class_classtpx[rownames(tab_class_classtpx) %in% colnames(tab_class_classtpx), ]))
misclass_classtpx <- 1 - (sum(diag(tab_class_classtpx[rownames(tab_class_classtpx) %in% colnames(tab_class_classtpx), ]))/ sum(tab_class_classtpx))
misclass_classtpx

print(tab_class_classtpx)


```

```{r echo=TRUE, eval=TRUE}
class_labs <- labels_class
known_samples <- inds_class

Topic_clus <- classtpx::class_topics(
    counts, 
    K=length(unique(cell_type)), 
    known_samples = known_samples,
    class_labs = class_labs,
    method="omega.fix",
    shrink=FALSE,
    shrink.method = 1,
    tol=0.0001,
    ord=FALSE)

save(Topic_clus, file="../rdas/deng_omega_fix.rda")

```


```{r echo=TRUE, eval=TRUE}

Topic_clus <- get(load("../rdas/deng_omega_fix.rda"))

omega <- Topic_clus$omega
annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(rownames(omega),
                        levels = rev( c("zy", "early2cell",
                                        "mid2cell", "late2cell",
                                        "4cell", "8cell", "16cell",
                                        "earlyblast","midblast",
                                         "lateblast") ) ) )

rownames(omega) <- annotation$sample_id;
cols1 <- c(rev(RColorBrewer::brewer.pal(12, "Paired"))[c(3,4,7,8,11,12,5,6,9,10)],
           RColorBrewer::brewer.pal(12, "Set3")[c(1,2,5,8,9)],
           RColorBrewer::brewer.pal(9, "Set1")[c(9,7)],
           RColorBrewer::brewer.pal(8, "Dark2")[c(3,4,8)])


CountClust::StructureGGplot(omega = omega,
                annotation = annotation,
                palette = cols1,
                yaxis_label = "Development Phase",
                order_sample = TRUE,
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

test_class_classtpx <- as.character(unique(cell_type))[apply(omega,1,function(x) which.max(x))];
tab_class_classtpx <- table(cell_type[-known_samples],
      test_class_classtpx[-known_samples]);

print(tab_class_classtpx)
sum(diag(tab_class_classtpx[rownames(tab_class_classtpx) %in% colnames(tab_class_classtpx), ]))
misclass_classtpx <- 1 - (sum(diag(tab_class_classtpx[rownames(tab_class_classtpx) %in% colnames(tab_class_classtpx), ]))/ sum(tab_class_classtpx))
misclass_classtpx

print(tab_class_classtpx)


```


## SVM

```{r}

voom_counts <- limma::voom(counts)$E;
training_data <- voom_counts[known_samples,]
test_data <- voom_counts[-(known_samples),]
tissue_type <- cell_type[known_samples]
gene_names <- featureNames(Deng2014MouseESC)
training.data.frame <- cbind.data.frame(training_data, tissue_type);
colnames(training.data.frame) <- c(gene_names, "tissue_type");

model <- svm(tissue_type ~ ., data = training.data.frame)

test_class_svm <- predict(model, test_data)


tab_class_svm <- table(test_class_svm, 
                    cell_type[-known_samples])

```

