---
title: 'Non model based approaches: Adaptive shrinkage'
author: "Kushal K Dey"
date: "May 12, 2016"
output: html_document
---

Here we consider a number of non-model based approaches and we apply these methods on the voom transformed RNA-seq data (with and without ash adjustment). We observe how the performance of the different classification methods compare for the ash shrunk and the non-ash versions of the voom transformed data.

```{r warning=FALSE, message=FALSE}
library(data.table)
library(e1071)
library(classtpx)
library(maptpx)
library(randomForest)
```

## Data Preparation (Arteries)

```{r message=FALSE, warning=FALSE}
gtex_data <- data.frame(fread("../data/GTEX_V6/cis_gene_expression.txt"));
matdata <- gtex_data[,-(1:2)];

tissue_labels=read.table("../data/GTEX_V6/samples_id.txt")[,3];

aorta_labels <- which(as.character(tissue_labels) == 'Artery - Aorta')
coronary_labels <- which(as.character(tissue_labels) == 'Artery - Coronary');
tibial_labels <- which(as.character(tissue_labels) == 'Artery - Tibial');
blood_labels <- which(as.character(tissue_labels) == 'Whole Blood')
uterus_labels <- which(as.character(tissue_labels) == 'Uterus')


pooled_data <- t(cbind(matdata[,aorta_labels],
                       matdata[,coronary_labels],
                       matdata[,tibial_labels],
                       matdata[,blood_labels],
                       matdata[,uterus_labels]))
```

```{r}
gene_names <- read.table("../data/GTEX_V6/gene_names_GTEX_V6.txt");
gene_names <- substring(gene_names[,1],1,15);

voom_matdata <- data.frame(fread("../data/GTEX_V6/voom_cis_gene_expression.txt"))
voom_matdata <- voom_matdata[,-1]

training_data <- t(cbind(voom_matdata[,aorta_labels[1:50]],
                         voom_matdata[,coronary_labels[1:50]],
                         voom_matdata[,tibial_labels[1:50]],
                         voom_matdata[, blood_labels[1:50]],
                         voom_matdata[, uterus_labels[1:50]]))

#training_data <- voom_shrunk_class_2

test_data <- t(cbind(voom_matdata[,aorta_labels[-(1:50)]],
                         voom_matdata[,coronary_labels[-(1:50)]],
                         voom_matdata[,tibial_labels[-(1:50)]],
                         voom_matdata[, blood_labels[-(1:50)]],
                         voom_matdata[, uterus_labels[-(1:50)]]))

tissue_type <- c(rep("Aorta",50), 
                 rep("Coronary",50),
                 rep("Tibial", 50),
                 rep("Blood", 50),
                 rep("Uterus", 50));

training.data.frame <- cbind.data.frame(training_data, tissue_type);
colnames(training.data.frame) <- c(gene_names, "tissue_type");

model <- svm(tissue_type ~ ., data = training.data.frame)

test_class_svm <- predict(model, test_data)

tab_class_svm <- table(test_class_svm, 
                c(rep("Aorta", length(aorta_labels)-50),   
                  rep("Coronary", length(coronary_labels)-50),
                  rep("Tibial", length(tibial_labels)-50),
                  rep("Blood", length(blood_labels)-50),
                  rep("Uterus", length(uterus_labels)-50)))

print(tab_class_svm)

misclass_svm <- sum(tab_class_svm[row(tab_class_svm)!=col(tab_class_svm)])/ sum(tab_class_svm)
misclass_svm


model <- randomForest(tissue_type ~ ., data = training.data.frame)
save(model, file="../rdas/arteries_blood_uterus_rf.rda")

test_class_rf <- predict(model, test_data)

```

```{r}
class_labs <- rep(1:5, each=50);
length_vec <- c(length(aorta_labels), length(coronary_labels),
                length(tibial_labels), length(blood_labels),
                length(uterus_labels))
cum_length_vec <- cumsum(length_vec)

known_samples <- as.vector(outer(1:50, c(0, cum_length_vec[1:(length(cum_length_vec)-1)]), "+"))


```

```{r}
voom2 <- function(counts){
  libsize.mat <- rep.col(rowSums(counts), dim(counts)[2]);
  voom.out <- log((counts+0.5), base=2) - log((libsize.mat+1), base=2)+ 6* log(10, base=2);
  return(voom.out)
}

rep.row<-function(x,n){
  matrix(rep(x,each=n),nrow=n)
}

rep.col<-function(x,n){
  matrix(rep(x,each=n), ncol=n, byrow=TRUE)
}

counts_class <- pooled_data[known_samples,];
voom_class <- voom2(counts_class);
mean_voom_features <- apply(voom_class, 2, mean);
    voom_class_adj <- voom_class - rep.row(mean_voom_features, dim(voom_class)[1])
    model_mat <- model.matrix(~as.factor(class_labs)-1) 
    
    beta_class <- matrix(0, dim(voom_class)[2], dim(model_mat)[2]);
    sebeta_class <- matrix(0, dim(voom_class)[2], dim(model_mat)[2])
    for(k in 1:dim(model_mat)[2]){
      model_mat_temp <- cbind(model_mat[,k]);
      limma.obj <- limma::lmFit(t(voom_class_adj), model_mat_temp)
      limma.obj <- limma::eBayes(limma.obj)
   #   mean_genes_limma <- apply(limma.obj$coefficients, 1, mean)
      beta_class[,k] <- as.matrix(limma.obj$coefficients[,1]);
      sebeta_class[,k] <- limma.obj$sigma*(as.matrix(limma.obj$stdev.unscaled[,1]));
    }
    
    ash_beta_class <- do.call(cbind, lapply(1:length(unique(class_labs)), 
                                            function(l) 
                                            {
                                              if(length(which(class_labs==l))==1){
                                                return(beta_class[,l])
                                              }else{
                                                return(suppressWarnings(ashr::ash(beta_class[,l], sebeta_class[,l], 
                                                                                  mixcompdist="normal")$PosteriorMean))
                                              }
                                            }));
 
voom_shrunk_class_2 <- matrix(0, dim(counts_class)[1], dim(counts_class)[2])
    
  for(i in 1:length(unique(class_labs))){
    voom_shrunk_class_2[which(class_labs==unique(class_labs)[i]),] <- 
             voom_class[which(class_labs==unique(class_labs)[i]),] - rep.row(as.vector(beta_class[,i]), length(which(class_labs==unique(class_labs)[i]))) + rep.row(as.vector(ash_beta_class[,i]), length(which(class_labs==unique(class_labs)[i])));
  }
    
    
```

```{r}
training_data <- voom_shrunk_class_2

#training_data <- voom_shrunk_class_2

test_data <- t(cbind(voom_matdata[,aorta_labels[-(1:50)]],
                         voom_matdata[,coronary_labels[-(1:50)]],
                         voom_matdata[,tibial_labels[-(1:50)]],
                         voom_matdata[, blood_labels[-(1:50)]],
                         voom_matdata[, uterus_labels[-(1:50)]]))

tissue_type <- c(rep("Aorta",50), 
                 rep("Coronary",50),
                 rep("Tibial", 50),
                 rep("Blood", 50),
                 rep("Uterus", 50));

training.data.frame <- cbind.data.frame(training_data, tissue_type);
colnames(training.data.frame) <- c(gene_names, "tissue_type");

model <- svm(tissue_type ~ ., data = training.data.frame)

test_class_svm <- predict(model, test_data)

tab_class_svm <- table(test_class_svm, 
                c(rep("Aorta", length(aorta_labels)-50),   
                  rep("Coronary", length(coronary_labels)-50),
                  rep("Tibial", length(tibial_labels)-50),
                  rep("Blood", length(blood_labels)-50),
                  rep("Uterus", length(uterus_labels)-50)))

print(tab_class_svm)

misclass_svm <- sum(tab_class_svm[row(tab_class_svm)!=col(tab_class_svm)])/ sum(tab_class_svm)
misclass_svm
```
