---
title: "Home"
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`


## Admixture clustering

* Human iPSCs multiple C1 replicates (Tung et al., 2016)
    * Human iPSC single cells
        * Endogeneous genes
             * [Structure plot of iPSC by batch, individual, cell cycle](cell_phase_analysis.html)
             * [Structure plot per individual and per individual & batch](structure_per_individual.html)
             * [Investigating the properties of genes - low counts](low_counts_genes.html)
             * [Investigating ERCC spike ins - RUV normalization](RUV_normalization.html)
             * [iPSC Structure plots before and after batch correction](batch_effect_all_genes.html)
        * Cell-cycle genes
             * [Cell-cycle scores](cell_cycle_score_analysis.html)
             * [Structure plots using before batch, individual correction](clustering_cell_cycle_genes.html)
             * [Structure plots after batch effect correction](batch_effect_cell_cycle_genes.html)
    * LCL data
      	*  [Endogeneous genes](lcl_structure.html)
      	*  [Cell-cycle genes](lcl_structure_cell_cycle_genes.html)
    * iPSC +LCL pooled data analysis
    	* [Admixture analysis (All genes + Cell cycle genes)](ipsc_lcl_structure.html)
    	* [Gene annotations of iPSC and LCL data](gene_annotations_ipsc_lcl.html)
    	* [Patterns of counts for cluster driving genes](gene_patterns_iPSC_LCL.html)
* Mouse ESCs staged for cell-cycle phase (Buettner et al., 2015)
  	* [Structure analysis](marioni_structure_all_genes.html)
  	* [Gene annotations](gene_annotations_marioni.html)
* Mouse embryos from oocyte to blastocyst stages (Deng et al., 2015)
  	* [Structure analysis](deng_structure_all_genes.html)
  	* [Gene annotations (K=7)](gene_annotations_deng.html)


-------------

## cellcycleR: Cell-cycle phase modeling  

* Methods and Materials
    * [Our model](../docs/cell-cycle/cell_reorder.pdf)
    * [Software package on GitHub](https://github.com/kkdey/cellcycleR)
* Exploratory analysis
    * Human iPSC data
        * [Macosko method](cell_ordering_iPSC.html)
        * [explore cell order](cell_cycle_score_analysis.html) 
* Sinusoidal fitting: applications
    * Human iPSC data (Tung et al. 2015)
        * Annotated cell cycle genes
            * 2015-11-04
                * [Estimation](yoav_cellcycleR_cellcycle_genes.html)
                * [Gene annotations](yoav_cellcycleR_postprocessing_cellcycle_genes.html) 
            * 2016-01-28, NA19239
                * [Estimation & annotations](yoav_cellcycleR_cellcycle_genes-2016-01-28.html)
                * [Compared with PCA](pca-sinu-ipsc-19239.html) 
        * All genes
            * 2015-11-11
                * [Estimation](yoav_cellcycleR_all_genes.html)
                * [Gene annotations](yoav_cellcycleR_postprocessing_all_genes.html)
            * 2016-01-31, NA19239
                * [Estimation & annotations](gilad-ipsc-all-genes-2016-01-31.html)
      	* [On non-ribosomal genes](yoav_cellycleR_non_ribosomal.html)  
  	    * [On CDC, cyclin and cell cycle genes](yoav_cellcycleR_cdc_cyclin.html)
    * [Human LCL data (Tung et al., 2015)](lcl_cellcycleR.html)
    * [Mouse ESCs (Buettner et al., 2015)](marioni_cellcycleR.html)
    * [Oscope data (Leng et al., 2015)](oscope_cellcycleR.html)
    * [Monocle data (Trapnell et al., 2014)](monocle_cellcycleR.html)
    * [Botstein yeast data (cdc, elu and alpha)](yeast_cellcycleR.html)
* Sinusoidal fitting: benchmark performance and simulation studies
    * PCA comparison with cellcycleR
        * [Simulation](pca_snr_compare.html)
        * [Gilad-2015-NA19101](pca-sinu-ipsc-19239.html)
    * [Runtime comparisons: parallel vs. lmFit](sin_cell_order_iter-runtime.html)
    * [Check how cell states and ribosomal genes may affect cellcycleR](cellcycler_with_ribosomal_sim.html)
    * [Testing Penalized Matrix Decomposition on cellcycle genes](pmd_cellcycler_test_1.html)
    * [Homegeneous correlation](gene-correlation-sinusoidal.html)
* Nonparametric smoothing: benchmark performance and simulation studies
    * [Wavelets](wavelet_validation_check.html)
    * [SMASH (smoothing wavelets)](smash_validation_check.html)
    * [LOESS (locally weighted scatterplot smoothing) ](loess_validation_check.html)
    * [Smoothing splines](splines_validation_check.html)
    * [Testing effectiveness of nonparametric cellcycleR](nonparametric_cellcycleR_tests.html)
    * [Comparison of different nonparameteric smoothers in cellcycleR](nonparametric_cellcycler_methods_compare.html)
    * [Nonparameteric smoothing - make ends meet](np_smoother_constraint.html)
* Nonparametric vs sinusoidal fitting
    * [Case Study 1](cellcycleR_compare1.html)
    * [Case Study 2](cellcycler_compare2.html)
    * [Case Study 3](cellcycleR_compare3.html)
    * [Case Study 4](cellcycleR_compare4.html)
* Cell-cycle phase classifer
    * [Multinomial lasso, Leng2015](oscope-classifer.html)

-------------

## classtpx: Semi-supervised classification

* Methods and Materials
    * [R package on GitHub](https://github.com/kkdey/classtpx)
* Simulation studies    
    * Simulation Runs (K=2) to validate classtpx - ([Simulation Run 1](classtpx_simulation_run_1.html),
    [Simulation Run 2](classtpx_simulation_run_2.html), [Simulation Run 3](classtpx_simulation_run_5.html))
    * Simulation Runs (K=3) to validate classtpx - ([Simulation Run 1](classtpx_simulation_run_3.html),
    [Simulation Run 2](classtpx_simulation_run_4.html))
* Applications
    * [Scialdone 2015 classtpx analysis](scialdone_classtpx.html)
    * [Buettner 2015 + Scialdone 2015 combined cell cycle data](buettner_scialdone_classtpx.html)
    * [Buettner 2015 data: half single cells from each phase used to manufacture bulk in training](buettner_classtpx_2015.html)
    * [Buettner 2015 data: half single cells used as it is from each phase in training ](buettner_classtpx_2015_2.html)
    * [Treutlin et al 2014 lung development data](treutlin_classtpx.html)
    * [Blakeley et al 2015 human blastocyst data](blakeley_classtpx.html)
    * [Deng et al 2014 using Blakeley 2015 as training](blakeley_deng_classtpx.html)
    * [Leng et al 2015 Oscope data](leng_classtpx.html)
    * [Leng et al 2015 Oscope data using Buettner et al 2015 data](leng_buettner_classtpx.html)
    * [classtpx vs SVM comparison on GTEx V6 data]
        * [Testis vs LCL](testis_lcl_classtpx_svm.html)
        * [Thyroid vs Adrenal Gland](thyroid_adrenal_classtpx_svm.html)
        * [Heart Atrial Appendage vs Heart Left Ventricle](heart_atrial_ventricle_classtpx_svm.html)
        * [Whole Blood vs Pancreas](blood_pancreas_classtpx_svm.html)
        * [Breast Mammary Tissue vs Ovary](breast_ovary_classtpx_svm.html)
        * [Brain Cerebellum and Brain Cerebellar Hemisphere](brain_cerebellum_hemisphere_classtpx_Svm.html)
        * [Arteries + Whole Blood + Uterus](arteries_blood_uterus_classtpx_svm.html)
        * [All arteries](arteries_classtpx_svm.html)

-------------


