---
title: 'Voom: model based approaches'
author: "Kushal K Dey"
date: "May 13, 2016"
output: html_document
---

```{r warning=FALSE, message=FALSE}
library(data.table)
library(e1071)
library(classtpx)
library(maptpx)
```

## Data Preparation (Arteries)

```{r message=FALSE, warning=FALSE}
gtex_data <- data.frame(fread("../data/GTEX_V6/cis_gene_expression.txt"));
matdata <- gtex_data[,-(1:2)];

tissue_labels=read.table("../data/GTEX_V6/samples_id.txt")[,3];

aorta_labels <- which(as.character(tissue_labels) == 'Artery - Aorta')
coronary_labels <- which(as.character(tissue_labels) == 'Artery - Coronary');
tibial_labels <- which(as.character(tissue_labels) == 'Artery - Tibial');

pooled_data <- t(cbind(matdata[,aorta_labels],
                       matdata[,coronary_labels],
                       matdata[,tibial_labels]))

```

```{r}
class_labs <- c(rep(1,50), rep(2,50), rep(3,50));
known_samples <- c(1:50, 
                   length(aorta_labels) + (1:50), 
                   length(aorta_labels)+length(coronary_labels)+ (1:50));

```

## Voom generator

```{r}
out <- class.voom_generator(pooled_data, known_samples, class_labs)
```

## normal likelihood model

```{r}
data <- out$voom_class;
mean_model <- out$voom_mean_class;
sigma_model <- do.call(cbind, lapply(1:dim(data)[2], function(l) tapply(data[,l], class_labs, sd)))

pooled_voom <- voom2(pooled_data)
test_voom <- pooled_voom[-(known_samples),];

loglik_test <- matrix(0, dim(test_voom)[1], length(unique(class_labs)))
  
for(k in 1:length(unique(class_labs))){
loglik_test[,k] <- rowSums(t(apply(test_voom, 1, function(x) dnorm(x, mean_model[k,], sigma_model[k,], log=TRUE))))
}

test_class <- c("Aorta", "Coronary", "Tibial")[apply(loglik_test,1,function(x) which.max(x))];
tab_class_model <- table(c(
      rep("Aorta", length(aorta_labels)), 
      rep("Coronary", length(coronary_labels)),
      rep("Tibial", length(tibial_labels)))[-known_samples],
      test_class);

print(tab_class_model)
misclass_model <- sum(tab_class_model[row(tab_class_model)!=col(tab_class_model)])/ sum(tab_class_model)
misclass_model

print(tab_class_model)

```

## normal (ash) likelihood model

```{r}
data <- out$voom_shrunk_class;
mean_model <- out$voom_shrunk_mean_class;
sigma_model <- do.call(cbind, lapply(1:dim(data)[2], function(l) tapply(data[,l], class_labs, sd)))

pooled_voom <- voom2(pooled_data)
test_voom <- pooled_voom[-(known_samples),];

loglik_test <- matrix(0, dim(test_voom)[1], length(unique(class_labs)))
  
for(k in 1:length(unique(class_labs))){
loglik_test[,k] <- rowSums(t(apply(test_voom, 1, function(x) dnorm(x, mean_model[k,], sigma_model[k,], log=TRUE))))
}

test_class <- c("Aorta", "Coronary", "Tibial")[apply(loglik_test,1,function(x) which.max(x))];
tab_class_model <- table(c(
      rep("Aorta", length(aorta_labels)), 
      rep("Coronary", length(coronary_labels)),
      rep("Tibial", length(tibial_labels)))[-known_samples],
      test_class);

print(tab_class_model)
misclass_model <- sum(tab_class_model[row(tab_class_model)!=col(tab_class_model)])/ sum(tab_class_model)
misclass_model

print(tab_class_model)

```

## poisson (ash) likelihood model

```{r}
lib_size_1 <- rowSums(pooled_data[known_samples,]);
lib_size <- rep(mean(lib_size_1), length(lib_size_1));
    counts_shrunk_matrix <- (2^{out$voom_class - 6*log(10, base=2)})*(rep.col(lib_size+1, dim(out$voom_shrunk_mean_class)[2])) - 0.5;
    counts_shrunk_matrix[counts_shrunk_matrix < 0]=1e-08;

counts_matrix <- pooled_data[known_samples,]   
df <- data.frame(class_labs, counts_shrunk_matrix)
library(dplyr)
out_df <- df %>% group_by(class_labs) %>% summarise_each(funs(mean));
model_lambda <- data.frame(out_df[,-1])

test_data <- pooled_data[-(known_samples),];

loglik_test <- matrix(0, dim(test_data)[1], length(unique(class_labs)))
  
for(k in 1:length(unique(class_labs))){
loglik_test[,k] <- rowSums(t(apply(test_data, 1, function(x) dpois(x, as.numeric(model_lambda[k,]), log=TRUE))))
}

test_class <- c("Aorta", "Coronary", "Tibial")[apply(loglik_test,1,function(x) which.max(x))];
tab_class_model <- table(c(
      rep("Aorta", length(aorta_labels)), 
      rep("Coronary", length(coronary_labels)),
      rep("Tibial", length(tibial_labels)))[-known_samples],
      test_class);

print(tab_class_model)
misclass_model <- sum(tab_class_model[row(tab_class_model)!=col(tab_class_model)])/ sum(tab_class_model)
misclass_model

print(tab_class_model)

```

```{r}
lib_size_1 <- rowSums(pooled_data[known_samples,]);
lib_size <- rep(mean(lib_size_1), length(lib_size_1));
    counts_shrunk_matrix <- (2^{out$voom_shrunk_class - 6*log(10, base=2)})*(rep.col(lib_size+1, dim(out$voom_shrunk_mean_class)[2])) - 0.5;
    counts_shrunk_matrix[counts_shrunk_matrix < 0]=1e-08;

df <- data.frame(class_labs, counts_shrunk_matrix)
library(dplyr)
out_mean <- df %>% group_by(class_labs) %>% summarise_each(funs(mean));
out_var <- df %>% group_by(class_labs) %>% summarise_each(funs(var));

out_mean_filtered <- as.matrix(out_mean[,-1]);
out_var_filtered <- as.matrix(out_var[,-1]);

negben_p <- (out_mean_filtered/out_var_filtered);
negben_p[negben_p > 1 ]=0.9999
negben_p[negben_p < 0] = 0.0001

negben_r <- ceiling(((negben_p)/(1-negben_p))*out_mean_filtered)

test_data <- pooled_data[-(known_samples),];

loglik_test <- matrix(0, dim(test_data)[1], length(unique(class_labs)))
  

for(k in 1:length(unique(class_labs))){
loglik_test[,k] <- rowSums(t(apply(test_data, 1, function(x) dnbinom(x, as.numeric(negben_r[k,]), as.numeric(negben_p[k,]), log=TRUE))))
}

test_class <- c("Aorta", "Coronary", "Tibial")[apply(loglik_test,1,function(x) which.max(x))];
tab_class_model <- table(c(
      rep("Aorta", length(aorta_labels)), 
      rep("Coronary", length(coronary_labels)),
      rep("Tibial", length(tibial_labels)))[-known_samples],
      test_class);

print(tab_class_model)
misclass_model <- sum(tab_class_model[row(tab_class_model)!=col(tab_class_model)])/ sum(tab_class_model)
misclass_model

print(tab_class_model)

```

